{{ range $tenantName, $tenantConfig := .Values.tenants }}
{{ if $tenantConfig.enabled }}
{{ $tenantGitopsNamespace := $.Values.platform.gitops.namespace }}
{{ $tenantPlatformRepository := $.Values.platform.gitops.repository }}
{{ $tenantPlatformRepositoryGitRef := $.Values.platform.gitops.ref }}
{{ $tenantPlatformRepositoryGitPath := $.Values.platform.gitops.path }}
{{ $tenantPlatformRepositorySecretRef := $.Values.platform.gitops.secretRef }}

{{ if $tenantConfig.gitops }}
{{ $tenantGitopsNamespace = coalesce $tenantConfig.gitops.namespace $tenantGitopsNamespace }}
{{ $tenantPlatformRepository = coalesce $tenantConfig.gitops.repository $tenantPlatformRepository }}
{{ $tenantPlatformRepositoryGitRef = coalesce $tenantConfig.gitops.ref $tenantPlatformRepositoryGitRef }}
{{ $tenantPlatformRepositoryGitPath = coalesce $tenantConfig.gitops.path $tenantPlatformRepositoryGitPath }}
{{ $tenantPlatformRepositorySecretRef = coalesce $tenantConfig.gitops.secretRef $tenantPlatformRepositorySecretRef }}
{{ end }}
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: {{ $tenantName }}
  namespace: {{ $tenantGitopsNamespace }}
spec:
  gitImplementation: go-git
  interval: 1m0s
  ref:
    branch: {{ $tenantPlatformRepositoryGitRef }}
  secretRef:
    name: {{ $tenantPlatformRepositorySecretRef }}
  timeout: 60s
  url: {{ $tenantPlatformRepository }}
{{ range $envName, $envConfig := $tenantConfig.environments }}
{{ if $envConfig.enabled }}
{{ $nameBase := (printf "%s-%s" $tenantName $envName) }}
{{ if $envConfig.gitops }}
{{ $tenantGitopsNamespace = coalesce $envConfig.gitops.namespace $tenantGitopsNamespace }}
{{ $tenantPlatformRepository = coalesce $envConfig.gitops.repository $tenantPlatformRepository }}
{{ $tenantPlatformRepositoryGitRef = coalesce $envConfig.gitops.ref $tenantPlatformRepositoryGitRef }}
{{ $tenantPlatformRepositoryGitPath = coalesce $envConfig.gitops.path $tenantPlatformRepositoryGitPath }}
{{ $tenantPlatformRepositorySecretRef = coalesce $envConfig.gitops.secretRef $tenantPlatformRepositorySecretRef }}
{{ end }}
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: {{ $nameBase }}
  namespace: {{ $tenantGitopsNamespace }}
spec:
  gitImplementation: go-git
  interval: 1m0s
  ref:
    branch: {{ $tenantPlatformRepositoryGitRef }}
  secretRef:
    name: {{ $tenantPlatformRepositorySecretRef }}
  timeout: 60s
  url: {{ $tenantPlatformRepository }}


{{ end }}
{{ end }}


{{ end }}
{{ end }}
