{{- define "app-extensions.scw-serviceaccount" -}}
{{- $name := (coalesce .value.name .key) }}
{{- $resourceName := (coalesce .value.resourceName .value.name .key) }}
apiVersion: iam.scaleway.upbound.io/v1alpha1
kind: Application
metadata:
  name: {{ $resourceName }}
  # annotations:
  #   crossplane.io/external-name: {{ coalesce .value.externalName $name }}
spec:
  forProvider:
    name: {{ coalesce .value.displayName $name }}
    description: "{{ coalesce .value.description (printf "SA generated by kube-core for: %s/%s/%s" .common.cluster.config.name .common.release.namespace ( coalesce .common.release.name $name)) }}"
    organizationId: {{ coalesce .value.organizationId .common.cloud.org.id }}
  deletionPolicy: {{ coalesce .value.deletionPolicy "Orphan" }}
  providerConfigRef:
    name: upbound-scw
{{- end }}
