apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "smocker.fullname" . }}
  labels:
    {{- include "smocker.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "smocker.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- if .Values.podAnnotations }}
      annotations:
        {{- with .Values.podAnnotations -}}
        {{ toYaml . | nindent 8 }}
        {{- end }}
      {{- end }}
      labels:
        {{- include "smocker.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          lifecycle:
            postStart:
              exec:
                command:
                - "sh"
                - "/usr/local/bin/init.sh"
          image: "{{ .Values.image.repository }}:{{ include "smocker.imageTag" . }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          # command: ["/opt/smocker"]
          command:
          - "sh"
          - "/usr/local/bin/start.sh"
          ports:
            - name: mock
              containerPort: 8080
              protocol: TCP
            - name: admin
              containerPort: 8081
              protocol: TCP
          env:
            - name: SMOCKER_LOG_LEVEL
              value: {{ .Values.logLevel }}
          volumeMounts:
            - name: startup
              mountPath: /usr/local/bin
            {{- if .Values.mocks }}
            - name: mocks
              mountPath: /mocks
            {{- end }}
          readinessProbe:
            httpGet:
              path: /version
              port: admin
            initialDelaySeconds: 2
            periodSeconds: 30
          livenessProbe:
            httpGet:
              path: /version
              port: admin
            initialDelaySeconds: 2
            periodSeconds: 30
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: startup
          configMap:
            name: {{ include "smocker.fullname" . }}
            defaultMode: 0755
        {{- if .Values.mocks }}
        - name: mocks
          configMap:
            name: {{ include "smocker.fullname" . }}-mock
        {{- end }}
