apiVersion: v2
name: logging-stack
description: A Helm chart for Kubernetes
type: application
version: 0.1.1
appVersion: "0.1.0"
dependencies:
- name: prometheus-elasticsearch-exporter
  alias: es-exporter
  repository: https://prometheus-community.github.io/helm-charts
  version: 4.12.0
  condition: es-exporter.enabled
